import {
  Home,
  Package,
  ShoppingCart,
  Users2,
  Settings,
  Grid,
  Loader2,
  Pen,
  Trash2,
  PlusCircle,
  MoreVertical,
  Mail,
  MessageCircle,
  Instagram,
  Twitter,
} from "lucide-react";

export const Icons = {
  mail: Mail,
  chat: MessageCircle,
  home: Home,
  twitter: Twitter,
  instagram: Instagram,
  package: Package,
  shoppingCart: ShoppingCart,
  users: Users2,
  settings: Settings,
  grid: Grid,
  spinner: Loader2,
  trash: Trash2,
  pen: Pen,
  plusCircle: PlusCircle,
  moreVertical: MoreVertical,
};
